Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -19.90                         -16.74
  y                         -34.47                         -29.00
  z                        -119.72                        -100.71
abs                         126.16                         106.13
                    unit:  μC/cm2                 unit:  μC/cm2
