Loewdin gross orbital population 

   mol#     mol  basisfunction     Loewdin GP     Loewdin GP
                                   for spin 1     for spin 2
      1     CN2           1a1g           0.98           0.98
                          1a1u           0.99           0.99
                          2a1g           0.93           0.88
                          3a1g           0.99           0.98
                          1e1u           0.99           0.98
                          1e1g           0.93           0.86
                          2a1u           0.88           0.81
                          3a1u           0.88           0.81
                          4a1g           0.04           0.03
                          2e1u           0.04           0.03
                          5a1g           0.01           0.01
                          4a1u           0.02           0.02
                         total           7.68           7.38

      2      Ni             4s           0.22           0.22
                         3d_xy           0.99           0.97
                         3d_yz           0.99           0.97
                        3d_z^2           0.91           0.41
                         3d_xz           0.99           0.97
                    3d_x^2-y^2           0.91           0.40
                         total           5.01           3.93

      3      Ni             4s           0.22           0.22
                         3d_xy           0.98           0.96
                         3d_yz           0.95           0.65
                        3d_z^2           0.94           0.66
                         3d_xz           0.99           0.97
                    3d_x^2-y^2           0.92           0.47
                         total           5.01           3.93

      4       N             2s           0.72           0.69
                          2p_y           0.72           0.68
                          2p_z           0.72           0.68
                          2p_x           0.74           0.71
                         total           2.89           2.76

      5       N             2s           0.72           0.69
                          2p_y           0.72           0.68
                          2p_z           0.72           0.68
                          2p_x           0.74           0.71
                         total           2.89           2.76

      6       C             2s           0.40           0.40
                          2p_y           0.48           0.46
                          2p_z           0.48           0.46
                          2p_x           0.53           0.53
                         total           1.90           1.85
