Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -19.91                         -17.08
  y                         -34.47                         -29.58
  z                        -119.49                        -102.53
abs                         125.94                         108.07
                    unit:  μC/cm2                 unit:  μC/cm2
