Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -19.91                         -16.75
  y                         -34.49                         -29.02
  z                        -119.59                        -100.68
abs                         126.04                         106.11
                    unit:  μC/cm2                 unit:  μC/cm2
