Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -19.90                         -17.08
  y                         -34.48                         -29.59
  z                        -119.47                        -102.54
abs                         125.93                         108.08
                    unit:  μC/cm2                 unit:  μC/cm2
