Loewdin Charges of the LCFO basis

 molecule#         molecule      Loewdin charge
         1              CN2               -1.07
         2               Ni                1.07
         3               Ni                1.07
         4                N               -0.66
         5                N               -0.66
         6                C                0.25

                      total                0.00
