Loewdin gross orbital population 

   mol#     mol  basisfunction     Loewdin GP     Loewdin GP
                                   for spin 1     for spin 2
      1     CN2           1a1g           0.98           0.98
                          1a1u           0.99           0.99
                          2a1g           0.91           0.91
                          1e1u           0.98           0.98
                          3a1g           0.98           0.98
                          1e1g           0.89           0.89
                          2a1u           0.85           0.85
                          3a1u           0.85           0.85
                          4a1g           0.04           0.04
                          2e1u           0.04           0.04
                          5a1g           0.01           0.01
                          4a1u           0.02           0.02
                         total           7.54           7.54

      2      Ni             4s           0.22           0.22
                         3d_xy           0.98           0.98
                         3d_yz           0.98           0.99
                        3d_z^2           0.37           0.93
                         3d_xz           0.98           0.98
                    3d_x^2-y^2           0.37           0.93
                         total           3.89           5.04

      3      Ni             4s           0.22           0.22
                         3d_xy           0.98           0.98
                         3d_yz           0.95           0.62
                        3d_z^2           0.95           0.64
                         3d_xz           0.99           0.98
                    3d_x^2-y^2           0.94           0.45
                         total           5.04           3.89

      4       N             2s           0.69           0.72
                          2p_y           0.71           0.69
                          2p_z           0.71           0.69
                          2p_x           0.71           0.73
                         total           2.82           2.84

      5       N             2s           0.72           0.69
                          2p_y           0.69           0.71
                          2p_z           0.69           0.71
                          2p_x           0.73           0.71
                         total           2.84           2.82

      6       C             2s           0.40           0.40
                          2p_y           0.47           0.47
                          2p_z           0.47           0.47
                          2p_x           0.53           0.53
                         total           1.88           1.88
