Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -20.17                         -17.32
  y                         -34.94                         -29.99
  z                        -120.28                        -103.24
abs                         126.87                         108.89
                    unit:  μC/cm2                 unit:  μC/cm2
