Loewdin Charges of the LCFO basis

 molecule#         molecule      Loewdin charge
         1              CN2               -1.02
         2               Ni                1.02
         3               Ni                1.01
         4                N               -0.60
         5                N               -0.61
         6                C                0.19

                      total               -0.00
