Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                         -19.92                         -16.76
  y                         -34.50                         -29.03
  z                        -119.60                        -100.71
abs                         126.06                         106.14
                    unit:  μC/cm2                 unit:  μC/cm2
